In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

# Загружаем датасет Breast Cancer
cancer = load_breast_cancer()

# Создаем DataFrame для удобства работы с данными
cancer_df = pd.DataFrame(data=cancer.data, columns=cancer.feature_names)
cancer_df['target'] = cancer.target

In [ ]:
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

<h1>Создание Тензора</h1>

In [ ]:
import torch

# Создаем тензор из списка
tensor_a = torch.tensor([1, 2, 3])
print(...)

# Создаем тензор из массива NumPy
import numpy as np
array_b = np.array([4, 5, 6])
tensor_b = torch.tensor(...)
print(...)

tensor([1, 2, 3])
tensor([4, 5, 6])


<h1>Основные операции</h1>

In [ ]:
# Сложение
result = ...
print(result)

# Умножение
result = ...
print(result)

# Поэлементное умножение
result = torch.mul(..., ...)
print(result)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([ 4, 10, 18])


<h1>Индексирование и срезы</h1>

In [ ]:
# Обращение к элементу по индексу
print(...)

# Срез
print(...)

# Индексирование по условию
print(...[tensor_a > 1])

tensor(1)
tensor([2, 3])
tensor([2, 3])


<h1>Операции над матрицами</h1>

In [ ]:
# Умножение матриц
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
result = torch.mm(..., ...)
print(result)

tensor([[19, 22],
        [43, 50]])


<h1>Решение задачи с помощью простой нейросети</h1>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
# Подготовка данных
X = cancer.data
y = cancer.target
# Разбиваем данные на трейн и тест выборки
...

# Нормализация данных
scaler = StandardScaler()
X_train = scaler.fit_transform(...)
X_test = scaler.transform(...)

In [ ]:
# Преобразование в тензоры PyTorch
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = ...
X_test = ...
y_test = ...

In [ ]:
# Определение нейронной сети, можете менять архитектуру как хотите)

class SimpleNN(nn.Module):
    def __init__(self, input_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(64, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return ...

In [ ]:
# Создание модели и выбор лосса и оптимизатора
input_size = X_train.shape[1]
model = ....
loss_fn = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=...)

In [ ]:
# Тренировка модели
num_epochs = ...

for epoch in range(num_epochs):
    # Forward pass
    # считаем предсказания
    outputs = ...

    # считаем лосс
    loss = ...

    # обнуляем градиенты оптимизатора
    ...

    # считаем градиенты лосса
    ...

    # делаем шаг оптимизатора
    ...

    # Выводим информацию о процессе обучения
    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [10/50], Loss: 0.1353
Epoch [20/50], Loss: 0.0740
Epoch [30/50], Loss: 0.0564
Epoch [40/50], Loss: 0.0434
Epoch [50/50], Loss: 0.0342


In [ ]:
# Оценка модели на тестовых данных
with torch.no_grad():
    y_pred = model(...)
    y_pred = (y_pred >= 0.5).float().view(-1)
    accuracy = ...

print(...)

Accuracy on test data: 0.9825
